# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'WQBackgroundLocateDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  # Pods for WQBackgroundLocateDemo
  pod 'AMap2DMap-NO-IDFA', '~> 4.6.0'
  pod 'AMapLocation-NO-IDFA', '~> 2.4.0'

  target 'WQBackgroundLocateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WQBackgroundLocateDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
